apiVersion: apps/v1
kind: Deployment
metadata:
  name: ckan
  labels:
    app: ckan
    app.kubernetes.io/name: ckan
spec:
  selector:
    matchLabels:
      app: ckan
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: ckan
    spec:
      containers:
        - name: ckan
          image: eu.gcr.io/dft-rsss-findtransptdata-dev/ckan_295:8c0f9a5
          ports:
            - containerPort: 5000
          env:
          - name: CKAN_SITE_ID
            value: "default"
          - name: CKAN_SITE_URL
            value: "https://123.160.120.34.bc.googleusercontent.com"
          - name: CKAN_PORT
            value: "5000"
          - name:  CKAN_MAX_UPLOAD_SIZE_MB
            value: "10"
          - name: CKAN__PLUGINS
            value: "envvars image_view text_view recline_view datastore datapusher nap_theme"
          - name: CKAN_SYSADMIN_NAME
            value: "sysadmin"
          - name: CKAN_SYSADMIN_PASSWORD
            value: "password"
          - name: CKAN_SYSADMIN_EMAIL
            value: "sysadmin@ckandev.com"
          - name: CKAN_SQLALCHEMY_URL
            value: "postgresql://ckan_default:ckanpassword@localhost/ckan_default_dev"
          - name: CKAN_SOLR_URL
            value: "http://solr-headless:8983/solr/ckan"
#          - name: MAINTENANCE_MODE
#            value: "true"
          - name: CKAN_DATASTORE_WRITE_URL
            value: "postgresql://ckan_default:ckanpassword@localhost/ckan_datastore_dev"
          - name: CKAN_DATASTORE_READ_URL
            value: "postgresql://datastore_ro:ckanpassword@localhost/ckan_datastore_dev"
          - name: CKAN__STORAGE_PATH
            value: "/var/lib/ckan"
          - name: CKAN_DATASETS_PER_PAGE
            value: "50"
          - name: FTD_TEST
            value: FTD_TEST_VAR
#          - name: CKAN_WEBASSETS_PATH
#            value: "/srv/app/data/webassets"
# Datapusher
          - name: CKAN__DATAPUSHER__URL
            value: "http://datapusher:8000"
          - name: CKAN__DATAPUSHER__CALLBACK_URL_BASE
            value: "http://ckan:5000/"
# Redis
          - name: CKAN__REDIS__URL
            value: "redis://10.13.225.99:6379/0"
          volumeMounts:
          - name: ckan-data
            mountPath: /var/lib/ckan
            readOnly: false
        # <INSTANCE_CONNECTION> here to include your GCP
        # project, the region of your Cloud SQL instance and the name
        # of your Cloud SQL instance. The format is
        # $PROJECT:$REGION:$INSTANCE
        # [START proxy_container]
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.17
          command: ["/cloud_sql_proxy",
                    "-instances=$(INSTANCE_CONNECTION)=tcp:5432",
                    "-credential_file=/secrets/cloudsql/key.json"]
          env:
          - name: INSTANCE_CONNECTION
            valueFrom:
              configMapKeyRef:
                key: connectionname
                name: connectionname
          # [START cloudsql_security_context]
          securityContext:
            runAsUser: 2  # non-root user
            allowPrivilegeEscalation: false
          # [END cloudsql_security_context]
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
        # [END proxy_container]
      # [START volumes]
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-sa-creds
        - name: ckan-data
          persistentVolumeClaim:
            claimName: ckan-pvc
      # [END volumes]
      initContainers:
      - name: set-volume-ownsership
        image: busybox:latest
        command: ["sh", "-c", "chown -R 92:92 /var/lib/ckan"] # 92 is the uid and gid of ckan user/group
        volumeMounts:
        - name: ckan-data
          mountPath: /var/lib/ckan
          readOnly: false
